server:
  port: 8100
  servlet:
    context-path: /deck-management

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: deck_management
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/poker_backend/protocol/openid-connect/certs
