server:
  port: 8300
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-management
          uri: lb://user_management:8101
          predicates:
            - Path=/user-management/**
        - id: deck-management
          uri: lb://deck_management:8100
          predicates:
            - Path=/deck-management/**
        - id: table-management
          uri: lb://table_management:8102
          predicates:
            - Path=/table-management/**