server:
  port: 8300
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-management
          uri: lb://user_management
          predicates:
            - Path=/user-management/**
        - id: deck-management
          uri: lb://deck_management
          predicates:
            - Path=/deck-management/**
        - id: table-management
          uri: lb://table_management
          predicates:
            - Path=/table-management/**
        - id: rsocket_server
          uri: lb:ws://rsocket-server:7000
          predicates:
            - Path=/rsocket**
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE