server:
  port: 8300
spring:
  cloud:
    gateway:
      routes:
        - id: user-management
          uri: http://localhost:8101
          predicates:
            - Path=/user-management/**
        - id: deck-management
          uri: http://localhost:8100
          predicates:
            - Path=/deck-management/**
        - id: table-management
          uri: http://localhost:8102
          predicates:
            - Path=/table-management/**